qlik-oss/enigma-go

.circleci/config.yml
examples/reload/monitor-progress/monitor-progress.go

The `monitor-progress` example did not fail even if the reload was unsuccessful. Added panic if err in the example and also copied the testdata needed in Circle CI.

Fail monitor-progress example on error and copy test data to engine in CCI

---

README.md

The documentation for installing the package used an incorrect flag `-U`. It should be lowercase.

Update flag for go get in README.md

---

README.md
schema/README.md
schema/cron.sh
schema/generate.go
schema/generate.sh

This PR adds a bash script for generating enigma-go based on a specific version of Qlik Analytics Engine and the JSON-RPC API.
Also added a cron job to make it easier to keep the enigma-go repo aligned with latest publish docker image of Qlik Analytics Engine.

Add script for generating enigma-go based on specific JSON-RPC API version

---

README.md

Link to examples section instead of using bare URL

---

.circleci/config.yml

The path to `golint` is now updated and enforced per https://github.com/golang/lint/issues/415.

Update golint path in Circle CI

---

.gitattributes

to avoid problems when using autocrlf = true/input and avoiding the following error when using dep
```
Solving failure:
(1) failed to clean up git repository at /gopath/pkg/dep/sources/https---github.com-qlik--oss-enigma--go - dirty? corrupted? status output:
M enigma-go.png
```

Always treat png as binary

---

examples/basics/events/README.md
examples/basics/events/events.go
session.go
session_test.go

Adds functionality to synchronously get changed and closed objects after using an enigma method. 
_How to use_
Add a pointer to a `ChangeLists{}` as value to the context passed to enigma
```golang
cl := ChangeLists{}
ctx := context.WithValue(context.Background(), ChangeListsKey{}, &cl)
```
When the enigma method returns, the changes can be accessed by e.g.
```golang
for handle := range cl.Changed {
// handle change on handle
}
```

Enable possibility for synchronously react on object changes

---

.circleci/config.yml

The Circle CI builds are failing on master when the mod cache is used. The cache should be restored before running any other steps otherwise some dependencies are already downloaded.

Restore cache before linting

---

examples/basics/events/events.go
go.sum
session.go
session_change_lists.go
session_change_lists_test.go

Added ChangeListsChannel/CloseChangeListsChannel functions in the session to allow listening on all change lists coming in to the session. The ChangeListsChannel takes an argument pushedOnly that allows you to get a channel that only received pushed change lists

Added support for listening on all change and close events for a session

---

go.sum
qix_generated.go
schema/generate.go
schema/generate.sh

This PR changes so that the generated code in enigma-go is generated from engines **OpenAPI v3 specification**.
It does not change any exterior functionality, only how the code is generated.
Closes #73

Generate enigma-go from OpenAPI v3 specification

---

session.go

After this PR the json-encoded traffic sent will no longer be HTML-escaped.
Solves downstream issue: https://github.com/qlik-oss/corectl/issues/346
Closes #79

Disable HTML-escaping in json encoding

---

renovate.json

When renovate bumps dependencies it should also run `go mod tidy` to clean up unused dependencies in `go.sum`.

Run go mod tidy when renovating

---

go.mod
go.sum

Timestamp was incorrect. They are validated as of 1.13.
The changes below were generated by `go mod init` running Go 1.13

Fixes 1.13 modules issue

---

error.go
error_test.go

ReplaceAll was introduce in go 1.12, using Replace with -1 instead to be backwards compatible.

Fix errors to be compatible with go 1.11

---

.circleci/config.yml

To secure the backwards compatibility in `enigma-go` we need to test against multiple golang versions in Circle CI. This PR adds jobs for versions `1.11`, `1.12` and `1.13` to the config.
This closes #95

Run CCI pipeline for multiple golang versions

---

renovate.json

Since we want to test multiple golang versions in Circle CI, then we need to disable renovate from bumping to newer golang versions.

Renovate should ignore golang version in cci

---

.circleci/config.yml
api-spec.json
release/release.sh
spec/generate.go

What the added code is meant to do is to run the API specification generation in the testing differently if the commit being tested has a tag on it. In that case, it should generate the spec with the version flag set to whatever the tag was.
I used `set +e` to ignore the exit code 128 you get from `git describe --tag` without tags. We should instead determine pass or fail based on the tests and on the git diff at the end.

Circleci API specification test

---

.circleci/config.yml
README.md
api-spec.json
release/release.sh
spec/generate.go

For compatibility issues regarding go's module handling we will remove the metadata information from future release tags.

Release tag no longer contains metadata

---

.circleci/config.yml

Circleci will now run the tests against golang 1.11, 1.12 and 1.13, not only 1.13.

Improved cci when releasing

---

session.go

Since order of case `select` is not guaranteed we got deadlock in a small percentage of cases due to `socketError` channel filling up when having multiple parallel write requests and the heartbeat picked the `<-q.outgoingMessages` instead of `<-socketError` case multiple subsequent times. Exiting the go-routine directly after writing to `socketError` mitigates the deadlock.

Avoid deadlocking mainSessionLoop

---

schema/generate.go

If object type info is missing in the spec we should fall back to `RemoteObject` instead of panic.

fix: Fall back to RemoteObject if type info is missing

---

float.go
float_test.go
schema/generate.go

Changing function to be a receiver instead of a pointer receiver. This will allow Marshal of any `enigma.Float64` or `*enigma.Float64` to be valid.
I did not update the Unmarshal function however, since it doesn't make sense to do so. If it is a normal receiver, we cannot modify anything outside of the function scope.

Change float marshal to normal receiver function

---

api-spec.json
error.go
qix_generated.go
schema/generate.go

Export `errorCodeLookup` so error codes can be looked up to get the string for code of e.g. `NxValidationError`.

Export error code lookup function

---

examples/basics/custom-type/README.md
examples/data/list-object/README.md
examples/data/string-expression/README.md
examples/reload/monitor-progress/README.md

Switching help.qlik.com links to qlik.dev instead - to promote the dev-portal

docs: switch to dev-portal docs links

---

float.go

This improve the performance of the custom float unmarshalling slightly compared to the goccy/go-json package.
On my machine:
(goccy)
```
> go test -bench=FloatUnmarshal -benchtime 60s
websocket: close 1000 (normal)goos: linux
goarch: amd64
pkg: github.com/qlik-oss/enigma-go/v3
cpu: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
BenchmarkFloatUnmarshal-12      304858903              237.8 ns/op
PASS
ok      github.com/qlik-oss/enigma-go/v3        96.879s
```
(strconv)
```
go test -bench=FloatUnmarshal -benchtime 60s
websocket: close 1000 (normal)goos: linux
goarch: amd64
pkg: github.com/qlik-oss/enigma-go/v3
cpu: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
BenchmarkFloatUnmarshal-12      343606368              209.1 ns/op
PASS
ok      github.com/qlik-oss/enigma-go/v3        93.551s
```
The …

fix: Use strconv in custom float unmarshalling

---

.circleci/config.yml
Makefile
default_dialer.go
dialer_test.go
socket_edge_case_test.go

This simplifies how the default-dialer works by removing the functionality for context-cancelling on the enigma-end.
The package we're using for websockets and their dependencies (the standard libraries `net` and `net/http`) use contexts correctly.
The simplification also ensures that the context is passed correctly with `DialContext` which enables the use of `httptrace.ClientTrace` - a valuable tool for debugging.

fix: Improve context handling

---

.circleci/config.yml

**Changes:**
- adds golang version `1.17` & `1.18` as target for e2e test
- uses the proper `cimg/go` convenience images from CCI
fixes https://github.com/qlik-oss/enigma-go/issues/208

chore: adding more golangs in ci tests

---

api-spec.json
json_rpc_types.go
session.go
session_change_lists.go
session_change_lists_test.go

Support `suspend` list as well in addition to existing `close` and `change` list.
Engine message example:
```
{"jsonrpc":"2.0","change":[1,2,3,4,5,6,7,8,9],"suspend":[1]}
```

Support suspend list

---

.circleci/config.yml
.github/workflows/release-enigma-go.yml
go.mod
go.sum
schema/generate.sh

Bump gha dependency `checkout` to `v4` and go-dep `golang.org/x/net` to `v0.25.0`.
No more auto-commit on each commit through generate-schema.

chore: update dependencies
